### ISSUE TITLE
Prepare release of version 0.11.0

### ISSUE THREAD

**Issue by jgliss** [metno/pyaerocom#325]
This issue is only for keeping an overview of what and what not should go into the upcoming release of version 0.11.0. All updates need to go via PR's into `main-dev`, so here only the PR's and associated issues are listed:

- [x] Model maps processing (#260)
- [x] Support for evaluation of conc in precip and wet deposition (#269)
- [x] Remove outlier removal in low-level colocation routines (#297)
- [x] Updates for CAMS84, that is, support for reading of MarcoPolo, EEA-NRT, AirNow; superobs processing; using HTAP masks for regional statistics (#310)
- [x] Updates for trends evaluation interface (#318)
- [x] Issue #327 
- [x] Issue #329

**Comment by jgliss** [comment]
@hansbrenna, perhaps you could also merge all your side branches into your main dev branch and we could include your stuff as well (also because of #324, which will come after release of 0.11.0 and will require quite some changes in the json structure)?

Could you make a draft PR for `Hans_main_dev` -> `main-dev` ?
